### ISSUE TITLE
Doesn't work for disabled elements

### ISSUE THREAD

**Issue by sethlivingston** [NV0/hover-inspect#1]
This is a great little tool. It would be nice to be able to hover over disabled elements, though.

**Comment by ilyashubin** [comment]
Hi, thanks for the report. I'm glad it helped someone :)
Disabled elements don't fire mouse events, thats how browsers work. I also want to inspect disabled elements, but I think there's no simple solution for this.

**Comment by oe** [comment]
I got a clue, listener `mousemove` event instead of `focus`, and use `document.elementFromPoint` to get the hovered element.

And, I have a question of codes: https://github.com/ilyashubin/hover-inspect/blob/7350e067db43dce49cdad4f6437d9f42abc42f05/app/hoverinspect.js#L46-L51

Why wrap the template with `template` tag?  It seems unnecessary.
